name: Check and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Project
      working-directory: ./src
      run: cargo check --verbose
    - name: Run Unit Tests
      working-directory: ./src
      run: cargo test --verbose